/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./models/base_building.glb ./base_building --simplify --types -K 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Building_Floor008: THREE.Mesh
    Building_Floor007: THREE.Mesh
    Building_Floor006: THREE.Mesh
    Building_Floor005: THREE.Mesh
    Building_Floor004: THREE.Mesh
    Building_Floor003: THREE.Mesh
    Building_Floor002: THREE.Mesh
    Building_Floor001: THREE.Mesh
    Building_Divider004: THREE.Mesh
    Building_Divider003: THREE.Mesh
    Building_Divider002: THREE.Mesh
    Building_Divider001: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Basebuilding(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/base_building.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh geometry={nodes.Building_Floor008.geometry} material={materials['Material.001']} position={[0, 39.398, -26.821]} />
        <mesh geometry={nodes.Building_Floor007.geometry} material={materials['Material.001']} position={[0, 36.711, -26.821]} />
        <mesh geometry={nodes.Building_Floor006.geometry} material={materials['Material.001']} position={[0, 31.308, -26.821]} />
        <mesh geometry={nodes.Building_Floor005.geometry} material={materials['Material.001']} position={[0, 28.56, -26.821]} />
        <mesh geometry={nodes.Building_Floor004.geometry} material={materials['Material.001']} position={[0, 23.198, -26.821]} />
        <mesh geometry={nodes.Building_Floor003.geometry} material={materials['Material.001']} position={[0, 20.482, -26.821]} />
        <mesh geometry={nodes.Building_Floor002.geometry} material={materials['Material.001']} position={[0, 12.393, -26.821]} />
        <mesh geometry={nodes.Building_Floor001.geometry} material={materials['Material.001']} position={[0, 15.106, -26.821]} />
        <mesh geometry={nodes.Building_Divider004.geometry} material={materials['Material.001']} position={[0, 42.066, -26.798]} />
        <mesh geometry={nodes.Building_Divider003.geometry} material={materials['Material.001']} position={[0, 34.012, -26.798]} />
        <mesh geometry={nodes.Building_Divider002.geometry} material={materials['Material.001']} position={[0, 25.825, -26.798]} />
        <mesh geometry={nodes.Building_Divider001.geometry} material={materials['Material.001']} position={[0, 17.801, -26.798]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/base_building.glb')
